apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learner-report.fullname" . }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "learner-report.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "learner-report.name" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
