apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learner-report.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "learner-report.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "learner-report.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
