apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "learner-report.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "learner-report.name" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "learner-report.name" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.mongo.repository }}:{{ .Values.image.mongo.tag }}"
          imagePullPolicy: {{ .Values.image.mongo.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.mongo.port }}
