apiVersion: v1
kind: Service
metadata:
  name: {{ include "learner-report.fullname" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ include "learner-report.name" . }}-frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
