replicaCount: 2

image:
  backend:
    repository: govind02420/learner-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  frontend:
    repository: govind02420/learner-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  mongo:
    repository: mongo
    tag: "6.0"
    pullPolicy: IfNotPresent

service:
  backend:
    type: ClusterIP
    port: 5000
  frontend:
    type: ClusterIP
    port: 3000
  mongo:
    type: ClusterIP
    port: 27017

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: learner.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
